version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
volumes:
    mongodata: